# Generated by Django 5.0.3 on 2024-03-05 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('devise', models.CharField(max_length=100)),
                ('superficie', models.FloatField()),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lespays.continent')),
            ],
        ),
    ]
